_commit: v1.12.1-6-gbf0c0a5
_src_path: /Users/crthomas/code/charlesthomas/homelab-template
additionalResources: jobs.yaml,priority-classes.yaml,recurring-jobs.yaml,storage-classes.yaml
backups: false
helm: false
homepageDescription: Storage Handler
homepageEnabled: true
homepageGroup: Kubernetes
homepageIcon: longhorn
homepageName: Longhorn
ingClass: nginx-internal
ingCname: ''
ingExtraAnnotations: ''
ingHost: longhorn.crt.house
ingName: longhorn
ingPathType: ImplementationSpecific
ingWebSockets: false
ingress: true
labels: ''
name: longhorn
namespace: longhorn
pvc: false
reloader: false
resources:
- configmaps.yaml
- crds.yaml
- daemon-sets.yaml
- deployments.yaml
- ingresses.yaml
- jobs.yaml
- rbac.yaml
- service-accounts.yaml
- services.yaml
service: false
serviceAccount: false
svcName: longhorn-frontend
svcPortNum: 80
upstreamURL: https://longhorn.io
url: https://github.com/charlesthomas/homelab-longhorn
