---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: longhorn

commonAnnotations:
  repo: https://github.com/charlesthomas/homelab-longhorn

resources:
- resources/ingresses.yaml
- resources/namespaces.yaml
- resources/storage-classes.yaml
helmCharts:
- name: longhorn
  namespace: longhorn
  releaseName: longhorn
  repo: https://charts.longhorn.io
  valuesFile: helm/values.yaml
  version: 1.5.3
