---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
    repo: https://github.com/charlesthomas/homelab-longhorn
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
  name: longhorn-post-upgrade
  namespace: longhorn
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 1
  template:
    metadata:
      annotations:
        repo: https://github.com/charlesthomas/homelab-longhorn
      labels:
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/name: longhorn
      name: longhorn-post-upgrade
    spec:
      containers:
        - command:
            - longhorn-manager
            - post-upgrade
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: longhornio/longhorn-manager:v1.10.1
          imagePullPolicy: IfNotPresent
          name: longhorn-post-upgrade
      priorityClassName: longhorn-critical
      restartPolicy: OnFailure
      serviceAccountName: longhorn-service-account
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-upgrade
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation,hook-failed
    repo: https://github.com/charlesthomas/homelab-longhorn
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
  name: longhorn-pre-upgrade
  namespace: longhorn
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 1
  template:
    metadata:
      annotations:
        repo: https://github.com/charlesthomas/homelab-longhorn
      labels:
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/name: longhorn
      name: longhorn-pre-upgrade
    spec:
      containers:
        - command:
            - longhorn-manager
            - pre-upgrade
          env:
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: longhornio/longhorn-manager:v1.10.1
          imagePullPolicy: IfNotPresent
          name: longhorn-pre-upgrade
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /host/proc/
              name: proc
      restartPolicy: OnFailure
      serviceAccountName: longhorn-service-account
      volumes:
        - hostPath:
            path: /proc/
          name: proc
---
apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    repo: https://github.com/charlesthomas/homelab-longhorn
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
  name: longhorn-uninstall
  namespace: longhorn
spec:
  activeDeadlineSeconds: 900
  backoffLimit: 1
  template:
    metadata:
      annotations:
        repo: https://github.com/charlesthomas/homelab-longhorn
      labels:
        app.kubernetes.io/instance: longhorn
        app.kubernetes.io/name: longhorn
      name: longhorn-uninstall
    spec:
      containers:
        - command:
            - longhorn-manager
            - uninstall
            - --force
          env:
            - name: LONGHORN_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: longhornio/longhorn-manager:v1.10.1
          imagePullPolicy: IfNotPresent
          name: longhorn-uninstall
      priorityClassName: longhorn-critical
      restartPolicy: Never
      serviceAccountName: longhorn-service-account
