---
apiVersion: scheduling.k8s.io/v1
description: Ensure Longhorn pods have the highest priority to prevent any unexpected eviction by the Kubernetes scheduler under node pressure
globalDefault: false
kind: PriorityClass
metadata:
  annotations:
    repo: https://github.com/charlesthomas/homelab-longhorn
  labels:
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
  name: longhorn-critical
preemptionPolicy: PreemptLowerPriority
value: 1000000000
